version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: django
    versions:
    - 2.2.13
