# Generated by Django 4.0 on 2021-12-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_category_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
